
[functions.create-ticket]
enabled = true
verify_jwt = true
import_map = "./functions/create_ticket/deno.json"
entrypoint = "./functions/create_ticket/index.ts"

[functions.updateUserProfile]
enabled = true
verify_jwt = true
import_map = "./functions/updateUserProfile/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/updateUserProfile/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/updateUserProfile/*.html" ]

[functions.gmail]
enabled = true
verify_jwt = true
import_map = "./functions/gmail/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/gmail/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/gmail/*.html" ]
